### PR TITLE
Created public event hooks

### PR DESCRIPTION
**Pull request by rain2o**
Creating public event triggers for each of the IAS events so external JS functions can bind to them.

### CODE REVIEW

**Comment by gabrielsomoza** [comment]
This is interesting, thanks for your contribution!

One quick question before moving forward with this: the `ias` object should be globally available through the `window` after `$(document).ready()`, so in theory IAS events can be listened to directly by calling `ias.on()`. Is that not possible in practice?

**Comment by rain2o** [comment]
That was my first thought as well, but after testing that theory it proved to be incorrect. I just went back and did some more testing and it seems the issue was that `init.phtml` was being loaded in after all other JS, so the global variable was showing as `undefined` even inside the `$(document).ready()`. So this change could still avoid that issue if the order of items isn't correct, but I have modified my layouts to work with the change now as well.

**Comment by rain2o** [comment]
Actually, I may have spoken too soon. I am loading the `init.phtml` template in after jQuery but before my Javascript, and tested with the above code and it is still finding `window.ias` to be undefined. Further testing shows that the global variable is being established after my code is executing. I'm wondering if it is due to it being established inside the anonymous function that is inside a `getScript`. I will continue to do some testing...

**Comment by gabrielsomoza** [comment]
Sure, some more testing wouldn't hurt, but I see the value of this PR anyway. 

What do you think about firing a single, *custom*, event once IAS is loaded? The event could pass IAS as a parameter and allow further hooks. That kind of decoupling of our events from IAS would probably simplify things a bit in some cases: e.g. if IAS introduces a new event in the future then the approach would allow people to immediately listen to it instead of waiting for us to ALSO implement it. What do you think?

**Comment by rain2o** [comment]
That makes sense. Since you are already triggering an event when IAS is loaded, you could just add the data to that trigger. Something like this? https://github.com/rain2o/Magento-InfiniteScroll/commit/ad1681bc651e6e1ec3f112a3e8b8f4bbfec433cd
Let me know if you want to submit a new pull request for this.

**Comment by gabrielsomoza** [comment]
Yes, exactly. In fact we'll merge that directly once the debug feature is tested.

Closing this one in favor of #140

**Comment by damian-pastorini** [comment]
I'm merging #140 but note that we don't need any custom event to access window.ias, you just need to listen the window.load instead of document.ready:
image

```
$j(document).ready(function() {
    console.log('document ready');
    console.log(window.ias);
});

$j(window).load(function() {
    console.log('window load jquery');
    console.log(window.ias);
});

Event.observe(window, "load", function(){
    console.log('window load prototype');
    console.log(window.ias);
});
```

**Comment by gabrielsomoza** [comment]
We discussed this internally, conclusion: listening to "infiniteScrollReady" (as proposed in this PR) is better than listening to "window.load" because the first one might get fired earlier.

**Pull request closed without merging**
