### PR TITLE
replace $j reference with jQuery

### PR DESCRIPTION
**Pull request by aurmil**
to fix https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/168

### CODE REVIEW

**Comment by gsomoza** [comment]
Thanks!

**Comment by damian-pastorini** [comment]
I need to test this, as far I remember I did it that way on purpose because other wise the trigger will not work in RDW (which is the only theme for what we need it).

**Comment by aurmil** [comment]
OK
this fix works for me, fixed the problem caused by using $j in my own custom theme

**Comment by gsomoza** [comment]
@damian-pastorini jQuery should always be available under "jQuery" (as long as it's loaded). The `jQuery.noConflict()` call exists only to avoid issues with the `$` alias. So generally speaking using `jQuery` should always be safe.

But do double-check just in case, thanks.

**Comment by aurmil** [comment]
PS: just to let you know that "jQuery" reference is used in RWD theme in persistent/remember_me_tooltip.phtml file
however, it's the only usage I found in this theme

but of course, please check on your side

thanks

**Comment by damian-pastorini** [comment]
@aurmil confirmed it doens't work with jQuery, it only works with $j, I'm still checking why.

**Comment by damian-pastorini** [comment]
Well, actually all the associated events are been triggered in:
skin/frontend/rwd/default/js/app.js
And everything is defined in $j(window), so basically that's why.
I'll include a validation to check if $j is defined to avoid issues with other themes that doens't use RWD as base or fallback.

**Comment by aurmil** [comment]
OK

it's strange taht using jQuery doesn't work
from [jQuery.noConflict()](https://api.jquery.com/jquery.noconflict/) docs: 

> If necessary, you can free up the jQuery name as well by passing true as an argument to the method.

the only noConflict call is made without parameter

jQuery is not defined at all in your scope? just for my own curiosity

**Comment by gsomoza** [comment]
1. Try using just `$` instead of `jQuery`, because in that context we know that `$` should work.
2. Otherwise try using `window.jQuery` and see what happens.

I expect both of the above to fail, otherwise the fact that it doesn't work with just `jQuery` would be very weird.

Finally, if none of the above works, try something like this and see if it works:

```javascript
var _jq = ($j && $j.fn && $j.fn.jquery !== null) ? $j : $; // prefer AWS's jQuery
_jq(window).trigger(/* etc */);
```

**Comment by damian-pastorini** [comment]
jQuery it self is not the problem but where the events are been assigned or triggered from.
$j is a variable so it's an specific instance of jQuery and if you define something inside that var like $j(window).trigger('delayed-resize', e); 'delayed-resize' will only exists in $j and not in jQuery.

To see this you can check the following lines in the console (tested in a clean M 1.9.2.4 installation with M1 sample data):
$j.event.global;
jQuery.event.global;

image

image

To prevent any issue in case you are not using RWD (where $j is defined) I just added a validation to check $j.
PR: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/170
@gsomoza could you please confirm to merge? thx!

**Comment by damian-pastorini** [comment]
Closing this, check https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/170

**Comment by aurmil** [comment]
OK thanks for the explanation

**Pull request closed without merging**
