### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by jzahedieh**
Very useful for quickly grabbing the latest development copy, I know `connect20/strategery_infinitescroll2` is on [Firegento](http://packages.firegento.com/#!/connect20/strategery) but I feel this is a must for a modern library.

### CODE REVIEW

**Comment by vtrmantovani** [comment]
+1

**Comment by gabrielsomoza** [comment]
@damian-pastorini could you test & merge this one and also incorporate some of the changes from PR #111 into the composer.json file?

**Comment by damian-pastorini** [comment]
@jzahedieh , could you update this branch so I could merge it please? Thanks!

**Comment by jzahedieh** [comment]
Hi @damian-pastorini I updated the branch and resolved the conflict, I used your composer.json as it will work.

FYI it is still called Magento Cron Scheduler also the project license conflicts should be AFL not GPL?

**Comment by gabrielsomoza** [comment]
Yes, license should be AFL and @damian-pastorini  make sure the name is correct in the composer.json file and any other files (not sure where "Magento Cron Scheduler" came from but it shouldn't be there).

**Pull request merged**
